replicaCount: 3

image:
  repository: ghcr.io/izual750/bso-training-webapp
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 9000

resources: {}

livenessProbe:
  tcpSocket:
    port: php

readinessProbe:
  tcpSocket:
    port: php

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

redis:
  host: redis.training.svc.cluster.local
  port: "6379"
  passwordSecret: redis
  passwordKey: redis-password