apiVersion: v1
kind: Service
metadata:
  name: my-php-service
  labels:
    {{- include "webapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: php
      protocol: TCP
      name: php
  selector:
    {{- include "webapp-chart.selectorLabels" . | nindent 4 }}
