{{- if .Values.ingress.main.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mychart.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.main.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.main.ingressClassName }}
  ingressClassName: {{ .Values.ingress.main.ingressClassName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.main.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "mychart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.main.tls }}
  tls:
    {{- toYaml .Values.ingress.main.tls | nindent 4 }}
  {{- end }}
{{- end }}