apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /usr/share/nginx/html;
      index index.php index.html;

      location / {
        try_files $uri $uri/ /main.php?$query_string;
      }

      location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass my-php-service:9000;
        fastcgi_index main.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
      }
    }
